# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# See https://circleci.com/docs/2.0/configuration-reference/ for configuration reference.
version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#nodejs
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: "Build"
          command: yarn build
      - run:
          name: "Run lint"
          command: yarn lint
      - run:
          name: "Run tests"
          command: yarn test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          # Add HEROKU_API_KEY and HEROKU_APP_NAME in CircleCI as environment variables
          # https://circleci.com/docs/2.0/env-vars/
          # DO NOT ADD THEM HERE!
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      # [task:advanced]: Add automatic deployment to Heroku here
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
